var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/batches/[id]/notes/route.js")
R.c("server/chunks/[root-of-the-server]__1ol9opa._.js")
R.c("server/chunks/src_0le27qw._.js")
R.c("server/chunks/[root-of-the-server]__1saz4v1._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0ywzsx8._.js")
R.c("server/chunks/src_062-bfp._.js")
R.c("server/chunks/_036dlxb._.js")
R.c("server/chunks/_0a2yohk._.js")
R.c("server/chunks/src_09xho5v._.js")
R.c("server/chunks/[root-of-the-server]__1h3cdeo._.js")
R.c("server/chunks/_1xjvole._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/_next-internal_server_app_api_batches_[id]_notes_route_actions_01i3sqn.js")
R.m(320555)
module.exports=R.m(320555).exports
