var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/discussions/[id]/reply/route.js")
R.c("server/chunks/[root-of-the-server]__1ol9opa._.js")
R.c("server/chunks/src_0le27qw._.js")
R.c("server/chunks/_1xjvole._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__0ywzsx8._.js")
R.c("server/chunks/[root-of-the-server]__17nz4de._.js")
R.c("server/chunks/src_09xho5v._.js")
R.c("server/chunks/_0a2yohk._.js")
R.c("server/chunks/[root-of-the-server]__1h3cdeo._.js")
R.c("server/chunks/_036dlxb._.js")
R.c("server/chunks/src_062-bfp._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/_next-internal_server_app_api_discussions_[id]_reply_route_actions_19zhlhs.js")
R.m(534860)
module.exports=R.m(534860).exports
