import type { Role, Permission } from "@/config/roles";

/**
 * Shared application types. Domain entity types are generated by Prisma (Step 2)
 * and imported from `@/generated/prisma`; this file holds cross-cutting shapes
 * that are not 1:1 with a table.
 */

export interface AuthUser {
  id: string;
  email: string;
  name: string;
  role: Role;
  avatarUrl?: string | null;
  permissions: Permission[];
}

export type { Role, Permission };

/** Generic async UI status for client stores/components. */
export type AsyncStatus = "idle" | "loading" | "success" | "error";

export interface SelectOption<T = string> {
  label: string;
  value: T;
  disabled?: boolean;
}

export interface DataTableQuery {
  page: number;
  pageSize: number;
  search?: string;
  sortBy?: string;
  sortDir?: "asc" | "desc";
}

export type Nullable<T> = T | null;
